= Basic Joystick Library for Arduino =

This library allows an Arduino board with USB capabilites to act as a 
Basic 2-axis Joystick. This library is based on the HID library.

This library is simplified based on my preferences from other similar
Arduino libraries. It does not include a full kitchen sink HID descriptor,
but rather only enough for a simple arcade stick or basic gamepad. It also
has a minimal code interface, which requires a little bit more C knowledge
than the average Arduino library.

To use it, include BasicJoystick.h in your sketch, then declare
a global or static instance of type JoyState_t. In the loop method,
update each of the members of this variable to their desired values
(e.g. axis value, button pressed, etc.), then pass the address of your
JoyState_t variable to setState()

The following is a simple example using only two buttons:

[source,c]
----
#include <BasicJoystick.h>

// PIN IO
#define DPAD_UP A5
#define DPAD_DOWN A4
#define DPAD_LEFT A3
#define DPAD_RIGHT A2

// Buttons using SNES terminology
#define BUTTON_Y 4
#define BUTTON_B 5

void setup() {
    pinMode(DPAD_LEFT, INPUT_PULLUP);
    pinMode(DPAD_UP, INPUT_PULLUP);
    pinMode(DPAD_RIGHT, INPUT_PULLUP);
    pinMode(DPAD_DOWN, INPUT_PULLUP);

    pinMode(BUTTON_Y, INPUT_PULLUP);
    pinMode(BUTTON_B, INPUT_PULLUP);
}

// Create joystick state structure for HID status reporting
JoyState_t state;

void loop() {
    // Assign button inputs to the state structure
    // Note that most buttons are active low (pressed = signal grounded)
    // so they require inversion.
    
    state.button_Y = !digitalRead(BUTTON_Y);
    state.button_B = !digitalRead(BUTTON_B);

    // Convert the digital joystick position into analog X/Y axis
    if (!digitalRead(DPAD_LEFT))
        state.xAxis = 0;
    else if (!digitalRead(DPAD_RIGHT))
        state.xAxis = 255;
    else
        state.xAxis = 127;

    if (!digitalRead(DPAD_UP))
        state.yAxis = 0;
    else if (!digitalRead(DPAD_DOWN))
        state.yAxis = 255;
    else
        state.yAxis = 127;
    
    // Set the state values and send back to the host device
    BasicJoystick.setState(&state);
}
----

The default variant of this library supports 10 buttons, using SNES-style
terminology. At least one other variant is maintained in a different
branch in this repository. Refer to BasicJoystick.h for the full set of 
supported button fields for the branch in use.

== License ==

Copyright (c) Ryan Armstrong. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
